### ISSUE TITLE
macOS 11 Big Sur Private Key Table is not available

### ISSUE THREAD

**Issue by aritgithub** [n0fate/chainbreaker#19] opened 2021-02-04 11:46 UTC
`python2.7 chainbreaker.py -p --dump-private-keys "/Users/xxx/Library/Keychains/login.keychain-db"
`

```
...
WARING - [!] Private Key Table is not available
INFO - 0 Private Keys
...
```

Is this a Big Sur issue?

**Comment by Ret2lib** [comment] 2021-02-09 06:07
Same issue on OSX catalina 10.15.7

**Comment by pencarsa** [comment] 2021-03-05 18:02
Will this be ever addressed?

**Comment by vetsin** [comment] 2021-04-25 16:29
I'm not sure what the actual issue is, but this super hack here makes it work:

https://github.com/vetsin/chainbreaker

The author will want to review why the `table_list` or `table_enum` isn't as expected (not sure which is wrong)

**Comment by jhonMalcom79** [comment] 2021-05-11 00:59
what version did you tried it on? I tried on Catalina and couldn't make it work

**Comment by vetsin** [comment] 2021-05-11 22:48
Made it work for my system - mojave 10.14.6 - can't tell you how to fix it right but you may need to do some debugging and change `if table_name == 23972:` to whatever value it is for you

**Comment by jhonMalcom79** [comment] 2021-05-12 00:53
I can get the value that is for me but should I set `table_name` to `16` or to something else? How did you get to the `16`?

Thanks @vetsin

**Comment by vetsin** [comment] 2021-05-12 04:16
You got past the bug most of us are having, you aren't unlocking it and I don't know why. I only did it on the System keychain and used the key file.

**Comment by Ret2lib** [comment] 2021-05-25 23:56
This worked for what I wanted.

https://github.com/gremwell/chainbreaker

**Comment by bobsoppe** [comment] 2021-09-21 07:08
To get a private key from the `system` keychain you need to disable SIP, so that you can access the SystemKey stored at `/var/db/SystemKey`

`sudo python ./chainbreaker.py --export-all --unlock-file /var/db/SystemKey --output out /Library/Keychains/System.keychain` would be able to export everything from the `system` keychain.

You still need to hardcode the correct table with the steps written in https://github.com/n0fate/chainbreaker/issues/19#issuecomment-839357165

**Comment by hypnoticpattern** [comment] 2021-09-22 03:19
The private keys I am trying to get are in the user folder like the ones @aritgithub was trying to retrieve.

**Comment by dKtKRVn** [comment] 2021-11-09 04:16
#22 done

**Comment by NgoKimPhu** [comment] 2022-02-17 04:58
@hypnoticpattern The fix works on my BigSur 11.6.2 too. The keys were correctly exported, your command only failed because you were missing `-inform DER`

**Comment by hypnoticpattern** [comment] 2022-02-17 05:15
@NgoKimPhu thanks for the fix. The certificates that were exported were malformed in my case. I tried to import them in other tools before trying openssl (e.g. Web proxies for MTLS) but got errors saying that they were malformed and then I used openssl to check the format (with the wrong command). I run the tool again last week on Monterey 12.2.1 and I am getting 0 Private Keys, 0 Public Keys and 10 x509 Certificates so there is something that it's not quite working for me. Out of curiosity. Are your private keys marked as non-exportable in key chain?

**Comment by hypnoticpattern** [comment] 2022-02-17 05:41
Can't reproduce the test I did in August but I just tried again and figured out why chainbreaker did not work on Monterey last week.  Monterey uses a different offset for private keys and I completely missed the BIG WARNING message in the tool output informing me of that. After adding a new `if` condition [here](https://github.com/n0fate/chainbreaker/blob/master/chainbreaker.py#L557) for offset 24328 (maybe specific for Monterey 12.2.1?) I was able to export the private keys. @NgoKimPhu thanks for making me look at it again!

**Comment by davidchoo12** [comment] 2022-05-09 09:54
Here is how I managed to export private keys for Big Sur 11.6.5:

1. Disable [System Integrity Protection](https://apple.stackexchange.com/a/208481)
2. Apply this [change](https://github.com/nkraetzschmar/chainbreaker/commit/75c52d1adf6e1931b7027bba98b43a1d2d946812)
3. `sudo python2 chainbreaker.py /Library/Keychains/System.keychain --unlock-file /var/db/SystemKey --dump-private-keys`

**Comment by pencarsa** [comment] 2022-05-09 17:30
I get private keys from System.keychain in the format name.key, 1KB each file, however, each is not readable. What am I missing ?

**Comment by hypnoticpattern** [comment] 2022-05-09 18:35
@pencarsa what OS version do you have? did you patch the code here based on the table number? Can you post the tool output?

**Comment by pencarsa** [comment] 2022-05-09 19:37
> @pencarsa what OS version do you have? did you patch the code [here](https://github.com/n0fate/chainbreaker/blob/master/chainbreaker.py#L557) based on the table number? Can you post the tool output?

@hypnoticpattern Thanks! Here are some details: 
OS: Monterey 12.3.1 
**Code:**
`556     def _get_base_address(self, table_name, offset=None):`
`557              if table_name >= 0x4000 and table_name < 0x5000:`
`558                    table_name = 15`
`559              if table_name >= 0x5000 and table_name < 0x6000:`
`560                   table_name = 16`
`561             base_address = _APPL_DB_HEADER.STRUCT.size + self._get_table_offset(table_name)`
`562             if offset:`
`563                 base_address += offset`

**Tool output:**
`ChainBreaker 2 - https://github.com/gaddie-3/chainbreaker`
`2022-05-09 21:22:03,434 - INFO - Runtime Command: chainbreaker.py -d /Library/Keychains/System.keychain --unlock-file /var/db/SystemKey --export-all --output out`
`2022-05-09 21:22:03,434 - INFO - Keychain: /Library/Keychains/System.keychain`
`2022-05-09 21:22:03,434 - INFO - Keychain MD5: dcbe47b235cf7fbe6d478b908f2db39e`
`2022-05-09 21:22:03,434 - INFO - Keychain 256: fb2b63894837680590f21b8ade98340b2a2f283e20324d963fcab49c794bf16d`
`2022-05-09 21:22:03,434 - INFO - Dump Start: 2022-05-09 21:22:00.508443`
`2022-05-09 21:22:03,434 - INFO - Dump Summary:`
`2022-05-09 21:22:03,434 - INFO - 	1 Keychain Password Hash`
`2022-05-09 21:22:03,435 - INFO - 	73 Generic Passwords`
`2022-05-09 21:22:03,435 - INFO - 	0 Internet Passwords`
`2022-05-09 21:22:03,435 - INFO - 	0 Appleshare Passwords`
`2022-05-09 21:22:03,435 - INFO - 	3 Private Keys`
`2022-05-09 21:22:03,435 - INFO - 	2 Public Keys`
`2022-05-09 21:22:03,435 - INFO - 	20 x509 Certificates`
`2022-05-09 21:22:03,435 - INFO - Dump End: 2022-05-09 21:22:03.434783`

Keys have a format: `somename.key`
Partial key file content:
`0Ç§ÇﬂA∞{â€ÆÅV¨ÿ@ŸèÊÉæ ∑8'N6–Ñä2OE¥©æw…œ0&b˜îê∞A¿e®˘p√y˛?˛E¶'¡«),˙‹“ú‘´πËN–zùÉ?ñÛ:?÷5íxÂˇ–ÈW¶WÖ‡í&ëß2ös}Ó+≥˝iå üvôG1O¬∞µÁö∆Ìh¶≤á®tZàk‰<áŸ¬öAF*6ÖÒ⁄ƒ6√úsjª§·Æ≤N™(ÁùñçUh`&ònØ«°˙Ω0®Rç7F∑+®O¶*≤~6Å9Vçü 81S‘E(≤tJª£πŸPhØop©Æg(∫ˆ¸Ú”Ç∞ìHŒSNÃ∫'F	UÜeØs3`·˚I)è¢LhÈ≤)ºˇıÕ∏ìœì;Óa»‹9˝ÍXPÒÎÖπíé‰P%◊√»M–º#ífgé©&i ¬ó/Í¬ºÑsZ¸ª‡PTCäõ[Î&›¥¿"≈⁄”@Ã∏®t˝!˝õ≥ojˇ\ö"9ÙEŒ≥¥“{âﬁ$‡æh6ÙsÇˆ=É⁄Á^ÍÓ‚ƒ$u~”`

**Comment by pencarsa** [comment] 2022-05-10 10:46
@hypnoticpattern forget about it, all works fine on Monterey. It was a matter of keys and crts conversion. For people who want to move these keys+crts as p12 files to another Mac's Keychain there are few steps to follow:
1. convert DER keys to PEM keys openssl rsa -inform DER -in name.key -out pem.key 
2. convert crt files to PEM certs openssl x509 -inform DER -in name.crt -out pem.cert -outform PEM
3. create pkcs12 file openssl pkcs12 -export -clcerts -inkey pem.key -in pem.cert -out name.p12 -name "yourname"

**Comment by n0fate** [comment] 2022-12-29 13:23
Sorry for being late. I fix some code for this issues. checkout #21

**Closed** 2022-12-29 13:51 UTC
